run once kdb.

GLOBAL ROCKET_HEIGHT IS 0.

FUNCTION FILE_EXISTS {
	DECLARE PARAMETER NAME.
	LIST FILES IN ALL_FILES.
	FOR F IN ALL_FILES {
		IF F = NAME {
			RETURN TRUE.
		}
	}
	RETURN FALSE.
}

IF FILE_EXISTS("DB.kdb") {
	SET DB TO KDB_LOAD("DB").
}
ELSE {
	SET DB TO LEXICON().
}

IF DB:HASKEY("ROCKET_HEIGHT") {
	SET ROCKET_HEIGHT TO DB["ROCKET_HEIGHT"].
}
ELSE {
	SET ROCKET_HEIGHT TO ALT:RADAR.
	SET DB["ROCKET_HEIGHT"] TO ROCKET_HEIGHT.
	
	KDB_SAVE("DB", DB).
}